name: Fetch FFmpeg core

on:
  workflow_dispatch:

jobs:
  fetch-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create folders
        run: |
          mkdir -p vendor/ffmpeg/umd
          mkdir -p vendor/ffmpeg/esm

      - name: Download FFmpeg core (UMD) & worker (ESM)
        run: |
          curl -L "https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd/ffmpeg-core.js" -o vendor/ffmpeg/umd/ffmpeg-core.js
          curl -L "https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd/ffmpeg-core.wasm" -o vendor/ffmpeg/umd/ffmpeg-core.wasm
          curl -L "https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd/ffmpeg-core.worker.js" -o vendor/ffmpeg/umd/ffmpeg-core.worker.js
          curl -L "https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@0.12.15/dist/esm/worker.js" -o vendor/ffmpeg/esm/worker.js

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vendor/ffmpeg
          git commit -m "Add ffmpeg core files (UMD + worker)" || echo "No changes"
          git push
